apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  DB_PASS: {{ .Values.secrets.DB_PASS | quote }}
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | quote }}
